# Generated by Django 4.2.23 on 2025-08-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpt_app', '0003_tip_downvotes_tip_upvotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-date'], 'permissions': [('can_downvote_tips', 'Can downvote any tip')]},
        ),
    ]
